In [203]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

data_path = 'C:/Users/admin/Documents/GitHub/3rd-ML100Days/data/'
df_train = pd.read_csv(data_path + 'train_data.csv')
df_test = pd.read_csv(data_path + 'test_features.csv')

from sklearn.preprocessing import LabelEncoder, MinMaxScaler
ids = df_test.name
train_Y = df_train['poi'] #Person of Interest
df_train = df_train.drop(['poi', 'name', 'email_address'],axis=1)
df_test = df_test.drop(['name', 'email_address'] , axis=1)
train_Y = LabelEncoder().fit_transform(train_Y)
train_no = df_train.shape[0]

df = pd.concat([df_train, df_test])
print(df.shape)
df.head(10)

(146, 19)

,bonus,deferral_payments,deferred_income,director_fees,exercised_stock_options,expenses,from_messages,from_poi_to_this_person,from_this_person_to_poi,loan_advances,long_term_incentive,other,restricted_stock,restricted_stock_deferred,salary,shared_receipt_with_poi,to_messages,total_payments,total_stock_value
0,1750000.0,NaN,-3504386.0,NaN,19794175.0,46950.0,18.0,42.0,4.0,NaN,1617011.0,174839.0,2748364.0,NaN,420636.0,864.0,905.0,505050.0,22542539.0
1,5600000.0,NaN,NaN,NaN,19250000.0,29336.0,108.0,88.0,30.0,NaN,1920000.0,22122.0,6843672.0,NaN,1111258.0,2042.0,3627.0,8682716.0,26093672.0
2,200000.0,NaN,-4167.0,NaN,1624396.0,22884.0,39.0,13.0,14.0,NaN,NaN,1573324.0,869220.0,NaN,211844.0,91.0,225.0,2003885.0,2493616.0
3,800000.0,NaN,NaN,NaN,NaN,118134.0,NaN,NaN,NaN,NaN,602671.0,907502.0,985032.0,NaN,224305.0,NaN,NaN,2652612.0,985032.0
4,1250000.0,NaN,-262500.0,NaN,NaN,35818.0,144.0,199.0,25.0,NaN,375304.0,486.0,126027.0,NaN,240189.0,2188.0,2598.0,1639297.0,126027.0
5,NaN,10259.0,NaN,NaN,30766064.0,77978.0,NaN,NaN,NaN,NaN,NaN,2856.0,NaN,NaN,NaN,NaN,NaN,91093.0,30766064.0
6,NaN,NaN,NaN,NaN,8308552.0,53947.0,NaN,NaN,NaN,NaN,NaN,147950.0,3576206.0,NaN,158403.0,NaN,NaN,360300.0,11884758.0
7,1200000.0,27610.0,-144062.0,NaN,NaN,16514.0,40.0,240.0,11.0,NaN,NaN,101740.0,698242.0,NaN,288542.0,1132.0,1758.0,1490344.0,698242.0
8,7000000.0,202911.0,-300000.0,NaN,34348384.0,99832.0,36.0,123.0,16.0,81525000.0,3600000.0,10359729.0,14761694.0,NaN,1072321.0,2411.0,4273.0,103559793.0,49110078.0
9,600000.0,NaN,NaN,NaN,384728.0,125978.0,16.0,52.0,6.0,NaN,71023.0,200308.0,393818.0,NaN,274975.0,874.0,873.0,1272284.0,778546.0

In [204]:
# 檢查 DataFrame 空缺值的狀態
def na_check(df_data):
    data_na = (df_data.isnull().sum() / len(df_data)) * 100
    data_na = data_na.drop(data_na[data_na == 0].index).sort_values(ascending=False)
    missing_data = pd.DataFrame({'Missing Ratio' :data_na})
    display(missing_data)
na_check(df)

                           Missing Ratio
loan_advances                  97.260274
director_fees                  88.356164
restricted_stock_deferred      87.671233
deferral_payments              73.287671
deferred_income                66.438356
long_term_incentive            54.794521
bonus                          43.835616
from_this_person_to_poi        41.095890
from_poi_to_this_person        41.095890
from_messages                  41.095890
shared_receipt_with_poi        41.095890
to_messages                    41.095890
other                          36.301370
expenses                       34.931507
salary                         34.931507
exercised_stock_options        30.136986
restricted_stock               24.657534
total_payments                 14.383562
total_stock_value              13.698630

In [205]:
# normalization
LEncoder = LabelEncoder()
MMEncoder = MinMaxScaler()

for c in df.columns:
    if df[c].dtype == 'object':
        df[c] = df[c].fillna('None')
        df[c] = LEncoder.fit_transform(df[c])
    #
    else:
        df[c] = df[c].fillna(df[c].mean())
    df[c] = MMEncoder.fit_transform(df[c].values.reshape(-1, 1))

df.head()

,bonus,deferral_payments,deferred_income,director_fees,exercised_stock_options,expenses,from_messages,from_poi_to_this_person,from_this_person_to_poi,loan_advances,long_term_incentive,other,restricted_stock,restricted_stock_deferred,salary,shared_receipt_with_poi,to_messages,total_payments,total_stock_value
0,0.017271,0.054222,0.874838,0.117199,0.063481,0.008940,0.000418,0.079545,0.006568,0.497606,0.031944,0.004098,0.040269,0.336177,0.015734,0.156188,0.056189,0.001629,0.051977
1,0.056850,0.054222,0.959287,0.117199,0.061736,0.005575,0.006687,0.166667,0.049261,0.497606,0.038198,0.000518,0.071078,0.336177,0.041596,0.369632,0.236549,0.028019,0.060149
2,0.001336,0.054222,0.999881,0.117199,0.005200,0.004343,0.001881,0.024621,0.022989,0.497606,0.028918,0.036874,0.026133,0.336177,0.007915,0.016126,0.011132,0.006466,0.005840
3,0.007505,0.054222,0.959287,0.117199,0.019193,0.022538,0.041571,0.122908,0.067705,0.497606,0.011010,0.021269,0.027004,0.336177,0.008382,0.212804,0.133638,0.008559,0.002368
4,0.012131,0.054222,0.990652,0.117199,0.019193,0.006814,0.009195,0.376894,0.041051,0.497606,0.006317,0.000011,0.020542,0.336177,0.008977,0.396086,0.168367,0.005290,0.000391

In [207]:
train_X = df[:train_no]
test_X = df[train_no:]

In [208]:
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from mlxtend.classifier import StackingClassifier

In [209]:
lr = LogisticRegression(tol=0.001, penalty='l2', fit_intercept=True, C=1.0)
lr.fit(train_X, train_Y)
lr_pred = lr.predict_proba(test_X)[:,1]

In [210]:
clf = RandomForestClassifier(n_estimators=100, min_samples_split=2, min_samples_leaf=1, max_features='sqrt', max_depth=6, bootstrap=True)
clf.fit(train_X, train_Y)
clf_pred = clf.predict_proba(test_X)[:,1]

In [211]:
gdbt = GradientBoostingClassifier(tol=100, subsample=0.75, n_estimators=250, max_features=19, max_depth=6, learning_rate=0.03)
gdbt.fit(train_X, train_Y)
gdbt_pred = gdbt.predict_proba(test_X)[:,1]

In [215]:

meta_estimator = GradientBoostingClassifier(tol=100, subsample=0.70, n_estimators=50, max_features='sqrt', max_depth=4, learning_rate=0.3)

In [217]:
stacking = StackingClassifier(classifiers = [lr, clf, gdbt], meta_classifier = meta_estimator)
stacking.fit(train_X, train_Y)
stacking_pred = stacking.predict_proba(test_X)

In [218]:
stacking = StackingClassifier(classifiers = [lr, clf, gdbt], meta_classifier = meta_estimator)
stacking.fit(train_X, train_Y)
stacking_pred = stacking.predict_proba(test_X)

In [220]:
blending_pred = lr_pred*0.15  + gdbt_pred*0.7 + clf_pred*0.15
sub = pd.DataFrame({'name': ids, 'poi': blending_pred})
sub.to_csv('sub_blending.csv', index=False)